#!/usr/bin/env bash
# this script create a backup of all databases in the mysql server

# Check if the password argument is provided
if [ -z "$1" ]; then
  echo "Usage: $0 <mysql_root_password>"
  exit 1
fi

MYSQL_ROOT_PASSWORD="$1"

# Generate the MySQL dump
sudo mysqldump -u root -p"$MYSQL_ROOT_PASSWORD" --all-databases > backup.sql


# Get the current date in the format day-month-year
CURRENT_DATE=$(date +%d-%m-%Y)

# Create a compressed archive of the MySQL dump
sudo tar -czvf "$CURRENT_DATE.tar.gz" backup.sql

echo "Backup and compression completed successfully. Archive created: $CURRENT_DATE.tar.gz"
