#!/usr/bin/env bash
# Write a Bash script that displays To infinity and beyond indefinitely.
var=1
trap 'echo "I am invincible!!!"' SIGTERM
while [ $var ] ; do
    echo "To infinity and beyond"
    sleep 2
done
