#!/usr/bin/env bash
# a Bash script that displays numbers from 1 to 100.

for num in {1..100}; do
    if [ $((num % 5)) == 0 ] && [ $((num % 3)) == 0 ]; then
        echo "FizzBuzz"
    elif [ $((num % 5)) -eq 0 ]; then
        echo "Buzz"
    elif [ $((num % 3)) -eq 0 ]; then
        echo "Fizz"
    else
        echo "$num"
    fi
    num=$(("$num"+1))
done
