#!/usr/bin/env bash
# This script displays the content of the current directory in list format
# we use cut -d '-' to split the string and -f2 to retrive the second potion

mylist=$(ls)

for i in $mylist; do
  echo "$i" | cut -d '-' -f2
done
